name: Parse LaTeX file for given command name
description: Reads a command value from a LaTeX *.tex file
inputs:
  latex_file:
    description: The LaTeX file where contains the command definition.
    required: true
    default: main.tex
    
  command_name:
    description: The command name to extract value
    required: true
    
outputs:
  command_value:
    description: The command value
        
runs:
  using: node12
  main: dist/index.js
